server:
  port: 9096
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true
    username: root
    password: Coder@9505
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:19092"
        - "localhost:29092"
        - "localhost:39092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}